// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1101:Prefix local calls with this", Justification = "<Pending>", Scope = "member", Target = "~M:LocalFriendzApi.Application.Response.PagedResponse`1.#ctor(`0,System.Int32,System.Int32,System.Int32,System.String)")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1101:Prefix local calls with this", Justification = "<Pending>", Scope = "member", Target = "~P:LocalFriendzApi.Application.Response.PagedResponse`1.TotalPages")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1401:Fields should be private", Justification = "<Pending>", Scope = "member", Target = "~F:LocalFriendzApi.Application.Response.Response`1.Code")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1101:Prefix local calls with this", Justification = "<Pending>", Scope = "member", Target = "~M:LocalFriendzApi.Application.Response.Response`1.#ctor(`0,System.Int32,System.String)")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1101:Prefix local calls with this", Justification = "<Pending>", Scope = "member", Target = "~M:LocalFriendzApi.Application.Response.Response`1.#ctor")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1101:Prefix local calls with this", Justification = "<Pending>", Scope = "member", Target = "~P:LocalFriendzApi.Application.Response.Response`1.IsSuccess")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1309:Field names should not begin with underscore", Justification = "<Pending>", Scope = "member", Target = "~F:LocalFriendzApi.Application.Services.ContactServices._contactRepository")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1309:Field names should not begin with underscore", Justification = "<Pending>", Scope = "member", Target = "~F:LocalFriendzApi.Application.Services.ContactServices._logger")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1101:Prefix local calls with this", Justification = "<Pending>", Scope = "member", Target = "~M:LocalFriendzApi.Application.Services.ContactServices.#ctor(LocalFriendzApi.Domain.IRepositories.IContactRepository,Microsoft.Extensions.Logging.ILogger{LocalFriendzApi.Application.Services.ContactServices})")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1101:Prefix local calls with this", Justification = "<Pending>", Scope = "member", Target = "~M:LocalFriendzApi.Application.Services.ContactServices.CreateContact(LocalFriendzApi.Application.Request.CreateContactRequest)~System.Threading.Tasks.Task{LocalFriendzApi.Application.Response.Response{LocalFriendzApi.Domain.Models.Contact}}")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1101:Prefix local calls with this", Justification = "<Pending>", Scope = "member", Target = "~M:LocalFriendzApi.Application.Services.ContactServices.DeleteContact(System.Guid)~System.Threading.Tasks.Task{LocalFriendzApi.Application.Response.Response{LocalFriendzApi.Domain.Models.Contact}}")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1101:Prefix local calls with this", Justification = "<Pending>", Scope = "member", Target = "~M:LocalFriendzApi.Application.Services.ContactServices.GetAllContactsWithAreaCode(LocalFriendzApi.Application.Request.GetAllContactRequest)~System.Threading.Tasks.Task{LocalFriendzApi.Application.Response.PagedResponse{System.Collections.Generic.List{LocalFriendzApi.Domain.Models.Contact}}}")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1101:Prefix local calls with this", Justification = "<Pending>", Scope = "member", Target = "~M:LocalFriendzApi.Application.Services.ContactServices.GetByFilter(System.String)~System.Threading.Tasks.Task{LocalFriendzApi.Application.Response.PagedResponse{System.Collections.Generic.List{LocalFriendzApi.Domain.Models.Contact}}}")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1101:Prefix local calls with this", Justification = "<Pending>", Scope = "member", Target = "~M:LocalFriendzApi.Application.Services.ContactServices.UpdateContact(System.Guid,LocalFriendzApi.Application.Request.UpdateContactRequest)~System.Threading.Tasks.Task{LocalFriendzApi.Application.Response.Response{LocalFriendzApi.Domain.Models.Contact}}")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1101:Prefix local calls with this", Justification = "<Pending>", Scope = "member", Target = "~M:LocalFriendzApi.Application.Validations.CreateContactRequestValidator.#ctor")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1413:Use trailing comma in multi-line initializers", Justification = "<Pending>", Scope = "member", Target = "~M:LocalFriendzApi.Application.Validations.CreateContactRequestValidator.HaveUniquePhoneOrEmail(LocalFriendzApi.Application.Request.CreateContactRequest)~System.Boolean")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1413:Use trailing comma in multi-line initializers", Justification = "<Pending>", Scope = "member", Target = "~M:LocalFriendzApi.Application.Validations.UpdateContactRequestValidator.HaveUniquePhoneOrEmail(LocalFriendzApi.Application.Request.UpdateContactRequest)~System.Boolean")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1101:Prefix local calls with this", Justification = "<Pending>", Scope = "member", Target = "~M:LocalFriendzApi.Application.Validations.UpdateContactRequestValidator.#ctor")]
