global:
  scrape_interval: 15s
  evaluation_interval: 30s

scrape_configs:
  - job_name: "localFriendzApi"
    scrape_interval: 5s
    static_configs:
      - targets: ["localfriendzapi.ui:8080"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
